### PR TITLE
Batter UI, Again!

### PR DESCRIPTION
**Pull request by manimonji**
making colors lighter

### CODE REVIEW

**Comment by flemming-n-larsen** [comment]
It is hard to see the recent changes, but it seems like the space  between the menu items have become a bit too large?

screenshot

**Comment by manimonji** [comment]
Does that looks bad?

**Comment by flemming-n-larsen** [comment]
> Does that look bad?

Of course, this is subjective and depends.
Perhaps it needs to be tested on a cell phone to see if the space is too much here.

**Comment by flemming-n-larsen** [comment]
I am closing this old PR.
Mainly due to the upgrade from VuePress v1 to v2 beta, where styling is now using SCSS.

**Pull request closed without merging**
