### PR TITLE
Batter UI

### PR DESCRIPTION
**Pull request by manimonji**
We just want BATTER UI .

### CODE REVIEW

**Review by flemming-n-larsen — CHANGES_REQUESTED** [review]
Hi @manimonji 
- I like the new scroll bar, which fits well into the "vuepress" design. :+1:
- I also like the hover effect for the links.
- And the background marking of with the side bar.

1) But the color for e.g. titles etc. is now too dark to read, at least on my screens. And of course the contrasts need to be high between background and text.

2) The nice [Fira font](https://fonts.google.com/specimen/Fira+Sans) does not seem work (when building the docs locally . See screenshot below). I guess the issue is with the @import url, which might not work in the .styl for VuePress. Something I might be able to help you out with, if you want me to?

You can view the result of your work by checking out the code and and `cd` your way to this directory: `/buildDocs/docs/.vuepress` and write:
``` 
npm run dev
```
You need at least [node.js](https://nodejs.org/en/) to be be installed on your system.

I will try to fix the issues (later today) so it get as close to your screen shot from the discussion thread: https://github.com/robocode-dev/tank-royale/discussions/18

This is the result I get:
Skærmbillede 2022-04-25 160254

**Comment by manimonji** [comment]
Hi @flemming-n-larsen  and thank you for feedback! 
i will fix this bug in this days but i have some work to do.

**Comment by flemming-n-larsen** [comment]
> Hi @flemming-n-larsen and thank you for feedback! I will fix this bug in this days but i have some work to do. I am strange with node.js and github. can you explain more? where i should run that command? in cmd?

Well, I could also do the fixes so it looks like this image here:
https://github.com/robocode-dev/tank-royale/discussions/18

If more stuff needs an update, you can just add some more screenshot. E.g. with this PR. :)

**Comment by flemming-n-larsen** [comment]
Implemented using VuePress from code.

**Pull request closed without merging**
